#!/usr/bin/env bash

destfile=""
[ ! -z "$1" ] && destfile="$1"

tmpfile=$(mktemp)
imgfile="$tmpfile.png"
mv $tmpfile $imgfile

echo "You can now use your mouse to grab a shot of your screen. Use Alt+TAB to switch screen. Once you are done come back here :)"
import $imgfile

echo "Screenshot is taken and places at the following path:"
echo $imgfile

if [ ! -z "$destfile" ]; then
  mv $imgfile $destfile
  echo "File saved at $destfile"
  exit
fi

read -p "Do you want to remove the file? y/N " keep

case "$keep" in
  "y")
    rm $imgfile
    echo 'File is deleted.'
  ;;
  *)
    echo 'File is kept.'
    echo $imgfile
  ;;
esac

